# Generated by Django 5.0.6 on 2024-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=False, verbose_name='artist'),
        ),
    ]
