# Generated by Django 5.0.6 on 2024-05-29 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_facebook_user_image_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='liked_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
