# Generated by Django 5.0.6 on 2024-05-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
