# Generated by Django 5.0.6 on 2024-05-28 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('year_created', models.PositiveIntegerField(default=0)),
                ('caption', models.TextField(blank=True, max_length=1000, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
