# Generated by Django 5.0.6 on 2024-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
