# Generated by Django 5.0.6 on 2024-05-29 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.ManyToManyField(related_name='curated_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
